set(SOURCES
test_argument_type.cpp
test_guarded_sequence_container.cpp
test_invokable.cpp
test_log.cpp
test_lru_cache.cpp
test_main.cpp
test_meta_class.cpp
test_object.cpp
test_object_extension.cpp
test_signal_slot.cpp
test_thread_pool.cpp
test_log_fixtures.hpp
test_meta_class_fixtures.hpp
test_utils.hpp
utils/domain_test_environment.hpp
utils/trace_printer_mock.hpp
)
