set(SOURCES
arguments/argument.cpp
arguments/packaged_arguments.cpp
log/trace.cpp
log/trace_printer.cpp
metadata/factory.cpp
metadata/metaclass.cpp
object.cpp
object_extensions/object_extension.cpp
object_extensions/signal.cpp
tasks/job.cpp
tasks/thread_pool.cpp
template.cpp
../include/stew/arguments/argument.hpp
../include/stew/arguments/detail/packaged_arguments.hpp
../include/stew/arguments/packaged_arguments.hpp
../include/stew/core/assert.hpp
../include/stew/core/pimpl.hpp
../include/stew/core/preprocessor.hpp
../include/stew/forwards.hpp
../include/stew/library_config.hpp
../include/stew/log/trace.hpp
../include/stew/log/trace_printer.hpp
../include/stew/meta/metadata/factory.hpp
../include/stew/meta/metadata/meta_object.hpp
../include/stew/meta/metadata/metaclass.hpp
../include/stew/meta/metadata/metaclass_impl.hpp
../include/stew/meta/object.hpp
../include/stew/meta/object_extensions/connection.hpp
../include/stew/meta/object_extensions/invokable.hpp
../include/stew/meta/object_extensions/object_extension.hpp
../include/stew/meta/object_extensions/signal.hpp
../include/stew/standalone/cache/detail/lru_cache.hpp
../include/stew/standalone/cache/lru_cache.hpp
../include/stew/standalone/cache/ttl_clock.hpp
../include/stew/standalone/container/detail/safe_queue.hpp
../include/stew/standalone/container/guarded_sequence_container.hpp
../include/stew/standalone/container/iterator.hpp
../include/stew/standalone/container/safe_queue.hpp
../include/stew/standalone/container/view.hpp
../include/stew/standalone/utility/algorithm.hpp
../include/stew/standalone/utility/concepts.hpp
../include/stew/standalone/utility/function_traits.hpp
../include/stew/standalone/utility/lockable.hpp
../include/stew/standalone/utility/reference_counted.hpp
../include/stew/standalone/utility/scope_value.hpp
../include/stew/standalone/utility/type_traits.hpp
../include/stew/stew.hpp
../include/stew/stew_api.hpp
../include/stew/tasks/job.hpp
../include/stew/tasks/thread_pool.hpp
)
