set(SOURCES
arguments/argument_type.cpp
log/trace.cpp
log/trace_printer.cpp
metadata/callable.cpp
metadata/factory.cpp
metadata/metaclass.cpp
metadata/metaobject.cpp
tasks/task.cpp
tasks/task_scheduler.cpp
template.cpp
threading.cpp
tasks/task_scheduler_private.h
../include/assert.hpp
../include/meta/arguments/argument_type.hpp
../include/meta/arguments/argument_type_impl.hpp
../include/meta/library_config.hpp
../include/meta/log/trace.hpp
../include/meta/log/trace_printer.hpp
../include/meta/meta.hpp
../include/meta/meta_api.hpp
../include/meta/metadata/callable.hpp
../include/meta/metadata/callable_impl.hpp
../include/meta/metadata/factory.hpp
../include/meta/metadata/metaclass.hpp
../include/meta/metadata/metaclass_impl.hpp
../include/meta/metadata/metaobject.hpp
../include/meta/tasks/task.hpp
../include/meta/tasks/task_scheduler.hpp
../include/meta/threading.hpp
../include/pimpl.hpp
../include/preprocessor.hpp
../include/utils/function_traits.hpp
../include/utils/lockable.hpp
../include/utils/scope_value.hpp
../include/utils/utility.hpp
../include/utils/vector.hpp
)
