name: CI

on: 
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DBUILD_GMOCK=OFF -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DBUILD_WITH_TESTS=ON ..
    - name: Build debug
      run: |
        cmake -DBUILD_GMOCK=OFF -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DBUILD_WITH_TESTS=ON ..
        cmake --build . --config Debug --target all -- -j8
    - name: Run unit tests
      run: |
        cd tests/unittest
        ./unittest

