name: CI

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: MacOS build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DBUILD_GMOCK=OFF -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DMOX_TESTS=ON ../
    - name: Build debug
      run: |
        cmake -DBUILD_GMOCK=OFF -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DMOX_TESTS=ON ../
        cmake --build . --config Debug --target all -- -j4
    - name: Run unit tests
      run: |
        cd tests/unittest
        ./unittest

